/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 */
import "./index.css";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import { flush, initEncryption } from "@prehospital-ems/sync-engine";
import { App } from "./App.js";

// Provision the PHI at-rest encryption key as early as possible. Started before
// render so it resolves before any component touches IndexedDB; database
// operations queue on the key until it's ready, so there's no race even if a
// read fires first. (Interim device-key mode — the app-lock PIN is added in #2.)
void initEncryption().catch((err) => {
  console.error("[crypto] failed to initialize at-rest encryption", err);
});

// Register the service worker (generated by vite-plugin-pwa).
// Auto-update on new deploy — no user prompt needed for a field tool.
registerSW({ immediate: true });

// Listen for FLUSH messages posted by the service worker's Background Sync
// handler — fires when the device reconnects after being offline.
if ("serviceWorker" in navigator) {
  navigator.serviceWorker.addEventListener("message", (event: MessageEvent<{ type: string }>) => {
    if (event.data?.type === "FLUSH") {
      void flush();
    }
  });
}

const root = document.getElementById("root");
if (!root) throw new Error("No #root element");
createRoot(root).render(<StrictMode><App /></StrictMode>);
