/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 */
import "./index.css";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import { flush } from "@prehospital-ems/sync-engine";
import { App } from "./App.js";

// The PHI at-rest key and app-lock state are provisioned by App via initAppLock:
// in device-key mode it installs the key immediately; once a PIN is set the app
// stays locked until it's entered. Database operations queue on the key gate, so
// a read firing before unlock never races. (App lock — issue #2.)

// Register the service worker (generated by vite-plugin-pwa).
// Auto-update on new deploy — no user prompt needed for a field tool.
registerSW({ immediate: true });

// Listen for FLUSH messages posted by the service worker's Background Sync
// handler — fires when the device reconnects after being offline.
if ("serviceWorker" in navigator) {
  navigator.serviceWorker.addEventListener("message", (event: MessageEvent<{ type: string }>) => {
    if (event.data?.type === "FLUSH") {
      void flush();
    }
  });
}

const root = document.getElementById("root");
if (!root) throw new Error("No #root element");
createRoot(root).render(<StrictMode><App /></StrictMode>);
