import "./index.css";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import { flush } from "@prehospital-ems/sync-engine";
import { App } from "./App.js";

// Register the service worker (generated by vite-plugin-pwa).
// Auto-update on new deploy — no user prompt needed for a field tool.
registerSW({ immediate: true });

// Listen for FLUSH messages posted by the service worker's Background Sync
// handler — fires when the device reconnects after being offline.
if ("serviceWorker" in navigator) {
  navigator.serviceWorker.addEventListener("message", (event: MessageEvent<{ type: string }>) => {
    if (event.data?.type === "FLUSH") {
      void flush();
    }
  });
}

const root = document.getElementById("root");
if (!root) throw new Error("No #root element");
createRoot(root).render(<StrictMode><App /></StrictMode>);
